import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { Toaster } from "@/components/ui/sonner"
import { NavbarDemo } from "@/components/navbar";
import AuthProvider from "./context/AuthProvider";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark:bg-gray-900`}
      >
         
       <AuthProvider>
         <ThemeProvider>
           <div className="fixed w-full top-0 z-50 ">
        <NavbarDemo  />
      </div>
          {children}
           <Toaster />
        </ThemeProvider>
       </AuthProvider>
      </body>
    </html>
  );
}
